language: php
php:
  - 5.3
  # - 5.4

env:
  - SYMFONY_VERSION=origin/master

before_script: 
  - curl -S http://getcomposer.org/installer | php
  - php composer.phar install

script: phpunit

notifications:
    webhooks: http://sonata-project.org/bundles/doctrine-orm-admin/master/travis
